### ISSUE TITLE
Item spawns not showing

### ISSUE THREAD

**Issue by aepkolol** [igromanru/gummy8unny-SoT-external-ESP#10]
Since latest update, chests, skulls and merchant items are only marked when picked up and dropped again. All offsets are correct, not sure whats happening. Skeletons, animals, players, ships and shipwrecks working fine. Changing `(name.find("BP_TreasureChest_Proxy")` to `(name.find("BP_TreasureChest")` shows item spawn point, but only after pickup.

**Comment by zanzo420** [comment]
I fixed this today please close this issue

**Comment by igromanru** [comment]
Please fix next time the comment for the auto updater.
This was the problem:
618b2b3dd0067f99d21da8256b643ccac389cb29
