### ISSUE TITLE
XMarksTheSpot maps not working since game updated to v1.2.0

### ISSUE THREAD

**Issue by zanzo420** [igromanru/gummy8unny-SoT-external-ESP#11]

**Comment by zanzo420** [comment]
I've been trying to figure out why this all of a sudden stopped working since the v1.2.0 update, especially since there were no changes to the offsets from v1.1.8 to 1.2.0... Anyone have any ideas?

**Comment by aepkolol** [comment]
I never used the ESP until the latest update dropped. I'm not 100% sure how it all worked before. If you wana go over some ideas you can join my discord server, https://discord.gg/Yzwrvx

**Comment by zanzo420** [comment]
FIXED by Zanzo420
(8/7/2018 @ 10:48AM PST)
